//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class district
    {
        public int id { get; set; }
        public string districtName { get; set; }
        public int typeArea_id { get; set; }
        public int province_id { get; set; }
        public Nullable<bool> districtStatus { get; set; }
    }
}
