//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class oderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public oderDetail()
        {
            this.products = new HashSet<product>();
        }
    
        public int id { get; set; }
        public string codeOder { get; set; }
        public string codeProduct { get; set; }
        public string productName { get; set; }
        public string userName { get; set; }
        public string productDescription { get; set; }
        public string productImage { get; set; }
        public string video { get; set; }
        public double price { get; set; }
        public int quantity { get; set; }
        public string detail { get; set; }
        public Nullable<int> oderId { get; set; }
    
        public virtual oder oder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> products { get; set; }
    }
}
