//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class oder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public oder()
        {
            this.oderDetails = new HashSet<oderDetail>();
        }
    
        public int id { get; set; }
        public string codeOder { get; set; }
        public string codeProduct { get; set; }
        public string userName { get; set; }
        public Nullable<bool> cartStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oderDetail> oderDetails { get; set; }
    }
}
