//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string productName { get; set; }
        public string codeProduct { get; set; }
        public string productDescription { get; set; }
        public string productImage { get; set; }
        public string video { get; set; }
        public double price { get; set; }
        public int quantity { get; set; }
        public string detail { get; set; }
        public Nullable<int> categoryProductId { get; set; }
        public Nullable<int> oderDetailId { get; set; }
    
        public virtual categoryProduct categoryProduct { get; set; }
        public virtual oderDetail oderDetail { get; set; }
    }
}
