//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string userAvatar { get; set; }
        public Nullable<System.DateTime> userBirthday { get; set; }
        public Nullable<bool> userGender { get; set; }
        public string userIdCard { get; set; }
        public string userPhone { get; set; }
        public string userAddress { get; set; }
        public string notes { get; set; }
        public Nullable<bool> userLevel { get; set; }
        public Nullable<bool> userStatus { get; set; }
    }
}
